name: Test Suite
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '15 17 15 * *'  # 15th of the month at 5:15pm UTC
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [10.x, 12.x]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Yarn
      run: |
        npm install -g yarn
        yarn --version
        yarn
    - name: Run Checks
      run: 
        yarn install
        yarn check
        yarn build
